name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:
    strategy:
      matrix:
        go: ['1.20', '1.19']
        os: [ubuntu-latest, macos-latest, windows-latest]

    name: Go ${{ matrix.go }} on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}

    - name: Run tests
      run: |
        go version
        go test -race ./...

    - name: Build binary and run it
      run: |
        go build
        ./gosnip 'fmt.Println("Test")'
